//
// Created by stuka on 13.05.2023.
//

#ifndef SUNGEARENGINE_GL46SHADER_H
#define SUNGEARENGINE_GL46SHADER_H

#include <glad/glad.h>
#include <string_view>

#include "SGCore/Graphics/API/IShader.h"
#include "SGCore/Graphics/SPIRV/ShaderReflection.h"

namespace SGCore
{
    /**
     * GL shader program of the legacy IShader interface.
     *
     * With m_useRHIUniforms (set by GL46Renderer) the shader is compiled from SGSLEVulkanizer
     * output — the same GLSL the RHI and the future Vulkan backend consume: loose uniforms live
     * in per-stage std140 blocks (`SGLegacyUniforms_<stage>`), samplers and blocks carry
     * `layout(binding)`. The IShader::useX("name", …) calls are then routed by reflection into
     * those uniform buffers (`name[i]` addressing supported), samplers keep going through
     * glUniform. Passes do not notice the difference; the data model is already the explicit-API
     * one. Without the flag (GL4Renderer) the shader compiles the raw translated GLSL as before.
     */
    class GL46Shader : public IShader
    {
        friend struct GL4Renderer;
        friend class GL46Renderer;

    public:
        ~GL46Shader() noexcept override;

        void bind() const noexcept override;

        void destroy() noexcept final;

        std::int32_t getShaderUniformLocation(const std::string& uniformName) noexcept override;

        void useUniformBuffer(const Ref<IUniformBuffer>&) override;
        void useTexture(const std::string& uniformName, const std::uint8_t& texBlock) final;

        void useMatrix(const std::string& uniformName, const glm::mat4& matrix) final;

        void useVectorf(const std::string& uniformName, const float& x, const float& y) override;
        void useVectorf(const std::string& uniformName,
                        const float& x, const float& y, const float& z) override;
        void useVectorf(const std::string& uniformName,
                        const float& x, const float& y, const float& z, const float& w) override;

        void useVectorf(const std::string& uniformName, const glm::vec2& vec) override;
        void useVectorf(const std::string& uniformName, const glm::vec3& vec) override;
        void useVectorf(const std::string& uniformName, const glm::vec4& vec) override;

        void useFloat(const std::string& uniformName, const float& f) override;
        void useInteger(const std::string& uniformName, const int& i) override;
        void useTextureBlock(const std::string& uniformName, const int& textureBlock) override;
        void useMaterialFactors(const IMaterial* material) override;
        
        bool isUniformExists(const std::string& uniformName) const noexcept;

        [[nodiscard]] const ShaderReflection& getReflection() const noexcept { return m_reflection; }

    private:
        /// A legacy uniform block generated by the vulkanizer, backed by a GL buffer.
        struct LegacyBlock
        {
            std::uint32_t m_binding { };
            std::uint32_t m_size { };
            GLuint m_buffer { };
        };

        struct LegacyMemberRef
        {
            std::size_t m_blockIndex { };
            std::uint32_t m_offset { };
            std::uint32_t m_size { };
            /// Stride of one element for arrays, 0 for scalars.
            std::uint32_t m_elementStride { };
            std::uint32_t m_arrayCount = 1;
        };

        GL46Shader() noexcept = default;

        void doCompile() override;

        GLuint compileSubShader(SGSLESubShaderType shaderType, const std::string& code);

        /// Builds legacy blocks and the member map from m_reflection after a successful link.
        void setupLegacyBlocks() noexcept;
        void destroyLegacyBlocks() noexcept;

        /// True if "name" / "name[i]" is a member of a generated legacy block.
        [[nodiscard]] bool isLegacyMember(std::string_view uniformName) const noexcept;

        /// Writes bytes into a legacy block member ("name[i]" addresses one element) in every stage
        /// block that has it; returns false if the name is not a legacy member.
        bool writeLegacy(std::string_view uniformName, const void* data, std::uint32_t size) noexcept;

        GLuint m_programHandle = 0;

        std::unordered_map<std::string, GLint> m_cachedLocations;

        // vertex, fragment, geometry, compute, tesselation control and tesselation evaluation shaders
        std::vector<std::pair<SGSLESubShaderType, GLuint>> m_subShadersHandles;

        bool m_useRHIUniforms { };
        ShaderReflection m_reflection;
        std::vector<LegacyBlock> m_legacyBlocks;
        std::unordered_map<std::string, std::vector<LegacyMemberRef>> m_legacyMembers;
    };
}

#endif //SUNGEARENGINE_GL46SHADER_H
